# This VM is here solely to provide an SSH server.

Vagrant.configure("2") do |config|
  # config.vm.box = "hashicorp/bionic64"
  config.vm.box = "ubuntu/jammy64"

  # Configuration with fixed local IP
  config.vm.network "private_network", ip: "192.168.56.10"

end
