---
name: macOS -- Build Python wheel using golang's gopy

on:
  push:
      branches:
          - main

defaults:
  run:
    shell: bash

jobs:
  call-lint:
    uses: ./.github/workflows/lint-on-macos.yaml

  build:
    runs-on: macos-13
    permissions:
        contents: write

    strategy:
      fail-fast: true
      matrix:
        go-version: [1.24.x]
        python3_version: [ 11, 12 ]
        arch_cibw_go:
          - [ "x86_64", "amd64" ]
          - [ "arm64", "arm64" ]
    steps:
        - uses: actions/checkout@v4

        - name: Setup Go
          uses: actions/setup-go@v4
          with:
              go-version: ${{ matrix.go-version }}
              cache-dependency-path: go.sum

        - name: install gopy
          run: go install github.com/go-python/gopy@v0.4.10

        - name: install goimports
          run: go install golang.org/x/tools/cmd/goimports@latest

        - name: Test with Go
          run: go test

        - name: Setup project files
          run: |
              rm -rf poetry.lock pyproject.toml
              cp setup_ci.py setup.py

        - name: install gopy
          run: go install github.com/go-python/gopy@v0.4.10

        - name: install goimports
          run: go install golang.org/x/tools/cmd/goimports@latest

        - name: install python 3.${{ matrix.python3_version }}
          run: |
            brew install --force --overwrite python@3.${{ matrix.python3_version }}
            ln -s /usr/local/opt/python@3.${{ matrix.python3_version }}/bin/python3.${{ matrix.python3_version }}  /usr/local/bin/python_for_build
            /usr/local/bin/python_for_build --version

        - name: install cibuildwheel and pybindgen
          run: /usr/local/bin/python_for_build -m pip install --break-system-packages cibuildwheel==2.21.3 pybindgen

        - name: build wheels
          run: /usr/local/bin/python_for_build -m cibuildwheel --output-dir wheelhouse
          env:
            CGO_ENABLED: 1  # build fails for arm if unset
            CIBW_ARCHS: ${{ matrix.arch_cibw_go[0] }}
            CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
            PYTHON_BINARY_PATH: /usr/local/bin/python_for_build
            CIBW_BUILD: "cp3${{ matrix.python3_version }}-*"
            CIBW_SKIP: "cp36-* cp37-* cp38-* cp39-* cp310-* cp313-* *-musllinux_x86_64"
            CIBW_ENVIRONMENT: >
              PATH=$PATH:/usr/local/go/bin
              GOARCH=${{ matrix.arch_cibw_go[1] }}
