---
name: E2E -- LXC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-lxc:
    name: E2E Ubuntu (lxc)
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - name: Setup project files
        run: |
          rm -rf poetry.lock pyproject.toml
          cat > pyproject.toml << 'EOF'
          [build-system]
          requires = ["setuptools>=40.8.0", "pybindgen"]
          build-backend = "setuptools.build_meta"
          EOF
          cp setup_ci.py setup.py

      - name: Build wheel
        uses: pypa/cibuildwheel@v3.4.1
        env:
          CIBW_BUILD: "cp311-*_x86_64"
          CIBW_SKIP: "*-musllinux_x86_64"
          CIBW_ARCHS: "native"
          CIBW_ENVIRONMENT: >
            PATH=$PATH:/usr/local/go/bin
          CIBW_BEFORE_ALL_LINUX: |
            curl -o go.tar.gz https://dl.google.com/go/go1.24.3.linux-amd64.tar.gz
            tar -C /usr/local -xzf go.tar.gz
            go install github.com/go-python/gopy@v0.4.10
            go install golang.org/x/tools/cmd/goimports@latest

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Initialize LXD
        run: |
          sudo lxd init --auto
          sudo iptables -P FORWARD ACCEPT

      - name: Install wheel
        run: pip install wheelhouse/*.whl

      - name: Run e2e tests
        run: python3 validate_ohpygossh.py --only=lxc
